version: "3"
services:
  backend:
    image: sentiment-backend
    container_name: backend
    ports:
      - "8000:8000"

  frontend:
    image: sentiment-frontend
    container_name: frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
