services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile   # <--- correct relative path
    dockerContext: backend
    plan: free
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: frontend/Dockerfile   # <--- correct relative path
    dockerContext: frontend
    plan: free
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://backend-xxxxx.onrender.com
